
name: Upload to S3
permissions: read-all 
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './schemas'
          destination_dir: 'schemas'